### ISSUE TITLE
Update CI docs

### ISSUE THREAD

**Issue by na--** [loadimpact/k6-docs#106]
A user [commented on](https://stackoverflow.com/questions/58297824/suggested-configuration-for-executing-k6-scripts-on-gilab-ci) the approach we suggest for using k6 in GitLab CI - our examples (https://gitlab.com/loadimpact/k6-gitlab-example, https://loadimpact.com/integrations/performance-testing-gitlab/#configuration) use `wget` to download a very old (v0.21.1) k6 version instead of the official docker image.

cc @ppcano, @robingustafsson, @markjmeier

**Comment by na--** [comment]
Not sure if any of this is still relevant after the new docs, `K6CLOUD_TOKEN` still seems to be present in some files: https://github.com/search?q=org%3Aloadimpact+K6CLOUD_TOKEN&type=Code

**Comment by simskij** [comment]
Yeah, this definitely needs to be updated. Good catch!

**Comment by ppcano** [comment]
The CI content was updated. Closing the issue.
