### ISSUE TITLE
Change branching strategy to trunk-based

### ISSUE THREAD

**Issue by simskij** [loadimpact/k6-docs#11]
To simplify the workflow, we should change the branching strategy to trunk-based + short-lived feature branches instead of the current `feature` -> `dev` (and staging) -> `master` (and prod) approach.

The new branching strategy means that features will be merged directly to master, which in turn will be released in staging. Tagging a commit in master with a version number will release it to production. For instance:

`master` will be released to staging, but not `feature/whatever`.
`v1.2.3` will be released to production, but not `an-arbitrary-tag`.

**Comment by imiric** [comment]
Could we increase the priority of this? This cherry-picking and dual PR approach is difficult, and can lead to discrepancy issues between staging and prod.

**Comment by simskij** [comment]
@ppcano - thoughts? ☝🏼

**Comment by simskij** [comment]
From a conversation with @ppcano regarding erroneous merges directly to master:

> When we move to github actions, I'll setup a check that fails if you try to merge to master from something else than develop. Effectively blocking you (or requiring you to actively override) the check to be able to merge to/from the "wrong" branch

**Comment by mostafa** [comment]
I am all pro this change.
