### ISSUE TITLE
K6 Docs: 14 Scenarios.md

### ISSUE THREAD

**Issue by M-Hoogie** [loadimpact/k6-docs#130]
I think i've detected a [sentence](https://github.com/loadimpact/k6-docs/blob/master/src/data/markdown/docs/01%20guides/02%20Using%20k6/14%20Scenarios.md
) that doesn't flow properly. 

> Scenarios allow us to make in-depth configurations to how VUs and iterations are scheduled, allowing k6 scenarios enable configuring how VUs and iterations are scheduled, making it possible to model diverse traffic patterns in load tests.

**Comment by simskij** [comment]
That's awesome! Thanks for highlighting it! 🎉 
Would you be interested in having a stab at rewriting it? I'd be happy to review any changes.
