### ISSUE TITLE
dead link

### ISSUE THREAD

**Issue by ryuichi1208** [loadimpact/k6-docs#149]
It seems that the link of the log tab page that comes out by searching with log is broken.

I created an issue because I don't know the correct URL.

<img width="611" alt="log" src="https://user-images.githubusercontent.com/35625782/98681825-84884b00-23a6-11eb-957c-9f868fe69cee.png">

dead links: https://k6.io/docs/cloud/analyzing-results/logs-tab

**Comment by simskij** [comment]
@ppcano @BolotskyDev - looks like we might need to invalidate the Algolia caches?

**Comment by ppcano** [comment]
You could set the page `slug` on the frontmatter.

https://github.com/loadimpact/k6-docs/blob/master/src/data/markdown/docs/03%20cloud/02%20Analyzing%20Results/07%20Logs%20Tab.md

The problem is that we are not sending the `slug` value to algolia.

**Comment by simskij** [comment]
solved by #154
