### ISSUE TITLE
JS API page not populated correctly

### ISSUE THREAD

**Issue by na--** [loadimpact/k6-docs#150]
In the course of contributing to https://github.com/loadimpact/k6-docs/pull/144, I noticed that the contents of the https://k6.io/docs/javascript-api page (or, rather, https://mdr-ci.staging.k6.io/docs/refs/pull/144/merge/javascript-api) were not being updated to include gRPC. 

This seems like a bug, since from what I can see, they are generated by this query, which should include the new gRPC JS page: https://github.com/loadimpact/k6-docs/blob/d36c6d4c01a21e198fa4b37969108daea8f039c8/src/templates/docs/javascript-api.js#L97-L100

**Comment by ppcano** [comment]
Closed by https://github.com/loadimpact/k6-docs/commit/6dfb68496e47c4c701b4ab9f02f973fb29a32169
