### ISSUE TITLE
Strip prompts from copied shell scripts.

### ISSUE THREAD

**Issue by simskij** [loadimpact/k6-docs#158]
> Hi Josh,
> 
> Thank you for the suggestion! We've decided to keep the dollar signs in the scripts for now. However, we would like to proceed with @BolotskyDev's idea about omitting them when copying. I'm creating a separate issue for that.
> 
> Closing this PR without merging. With that said, I'd like to thank you again for the excellent contribution. It definitely got us thinking through the UX.
> 
> Best,
> Simme

_Originally posted by @simskij in https://github.com/loadimpact/k6-docs/issues/146#issuecomment-730471676_

I think you are most suited to decide the best path forward, @BolotskyDev, so I'm happy to leave this in your hands.

**Comment by BolotskyDev** [comment]
Sure, don't worry about a thing 👌
