### ISSUE TITLE
Add .nvmrc file to specify which node version is required

### ISSUE THREAD

**Issue by sniku** [loadimpact/k6-docs#173]
Node v11.10.1 stopped working for me (not sure why). 
Node v13.7 doesn't work due to one of the dependencies not working.

It would be good to specify which Node version is supported. The easiest way is to create a `.nvmrc` file like this
`node -v > .nvmrc`

**Comment by simskij** [comment]
Great idea! We should also add the engine tag to our package.json to make sure it applies to non-nvm users as well. 👍🏻
