### ISSUE TITLE
missing error code from the doc website

### ISSUE THREAD

**Issue by sdhoward** [loadimpact/k6-docs#177]
The [error codes list](https://k6.io/docs/javascript-api/error-codes/) is missing information about error code 1213.

The module containing that code is [here](https://github.com/loadimpact/k6/blob/master/lib/netext/httpext/error_codes.go#L61).

There may or may not be others missing; that's the one I noticed.

Thanks!

**Comment by ppcano** [comment]
@sdhoward Thanks for reporting! 

Closed by https://github.com/loadimpact/k6-docs/commit/1b15226b900f1033f35085b9f05d854bdbd98a8b.
