### ISSUE TITLE
Add FormData example

### ISSUE THREAD

**Issue by na--** [loadimpact/k6-docs#203]
After https://github.com/loadimpact/k6/pull/1800 and https://github.com/loadimpact/jslib.k6.io/pull/21 are merged (i.e. k6 v0.31.0), we should add an example that demonstrates how to build advanced `multipart/form-data` request bodies with them. As evidenced by https://github.com/loadimpact/k6/issues/747, https://github.com/loadimpact/k6/issues/843, https://github.com/loadimpact/k6/issues/1375, https://github.com/loadimpact/k6/issues/1382, https://github.com/loadimpact/k6/issues/1571, https://github.com/loadimpact/k6/issues/1784, the current k6 HTTP API is quite restricted and can't cover a lot of corner cases... :disappointed: We'll close these issues (https://github.com/loadimpact/k6/pull/1800#issuecomment-768157584), so we probably should also add warning messages in https://k6.io/docs/javascript-api/k6-http/file-data-filename-contenttype and https://k6.io/docs/javascript-api/k6-http/filedata to use the JS polyfill for the corner cases the Go API can't cover.

At some future point, we'll try to fix all of these deficiencies with a new and better k6 JS API for HTTP requests, but until then this polyfill will likely be sufficient for 99% of users, with almost no downsides. So, we should document it properly.

**Comment by imiric** [comment]
:+1: I was planning to pick this up starting today. Too soon?

The polyfill works even without #1800, since it only needs `ArrayBuffer` support in request bodies, which is in v0.30.0. So the docs for this could be released whenever the jslib PR is released (this/next week?).

**Comment by na--** [comment]
Yeah, I didn't realize this, but that's awesome! Maybe some of the issues above wouldn't be closed until we release k6 v0.31.0, but most should be fine with what we have in k6 v0.30.0. I'll make sure to review https://github.com/loadimpact/jslib.k6.io/pull/21 tomorrow then.
