### ISSUE TITLE
gatsby-plugin-prefetch-google-fonts breaks build

### ISSUE THREAD

**Issue by imiric** [loadimpact/k6-docs#32]
[The latest `develop` build failed](https://circleci.com/gh/loadimpact/k6-docs/962) during `gatsby build --prefix-paths` with:

```
Error: ENOENT: no such file or directory, stat '.cache/google-fonts/docs/fonts
```

I was able to reproduce this locally, after a fresh `npm install`.

It seems that this plugin [has been deprecated](https://github.com/escaladesports/legacy-gatsby-plugin-prefetch-google-fonts/commit/b562fae743ef08a1e5b848a319574592ba9556f7) (and hidden behind a private repo?), and [others are having similar issues](https://github.com/escaladesports/legacy-gatsby-plugin-prefetch-google-fonts/issues/2), so we should probably abandon it. Not sure why this is only failing now, though... Probably a change on Google's side.

A suggested alternative in that issue is to use [gatsby-plugin-google-fonts](https://www.gatsbyjs.org/packages/gatsby-plugin-google-fonts/), but that one doesn't download fonts but links to Google's CDN in the CSS (e.g. `src: url(https://fonts.gstatic.com...)`). Which we might want to consider doing anyway.

**Comment by ppcano** [comment]
@BolotskyDev I don't know the current status. can this be closed now?

**Comment by BolotskyDev** [comment]
@ppcano resolved [here](https://github.com/loadimpact/k6-docs/commit/e0216e4422bdefe5277fbf7983c0c8bd780d7296#diff-b9e136416b90437fa1dac910280b45fc), closing
