### ISSUE TITLE
react-sticky throws "Uncaught TypeError: Cannot read property 'getBoundingClientRect' of undefined"

### ISSUE THREAD

**Issue by sniku** [loadimpact/k6-docs#45]
This is a low priority issue because it appears to be benign. 
![image](https://user-images.githubusercontent.com/442646/85790124-ff223800-b72f-11ea-8b4f-05b2927d4a16.png)

Example page where the error appears: https://k6.io/docs/javascript-api/k6-http/batch-requests

**Comment by BolotskyDev** [comment]
Resolved in #68, closing the issue
