### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by na--** [loadimpact/k6-docs#60]
@MStoykov mentioned these in the chat:

> https://k6.io/docs/cloud/analyzing-results/test-comparison#phase-2---baseline-testing-scaling-your-tests-and-complex-cases from the same page this is the 1st link on the page with text baseline
> https://k6.io/docs/testing-guides/load-testing-websites#what-k6-does-not the link is on the bottom of the same page

also, I noticed that the "Cloud support chat" from the little help popup in the bottom right is broken, leading to https://k6.io/docs/contact instead of presumably https://k6.io/contact?
![Screenshot_2020-07-14 k6 Documentation](https://user-images.githubusercontent.com/3336773/87423662-586ce100-c5e3-11ea-80a2-70a2e1ddf668.png)

**Comment by ppcano** [comment]
The first two broken links are fixed by https://github.com/loadimpact/k6-docs/commit/9a0e41884d3f8d86cd7816f501a1db36b001541d

**Comment by BolotskyDev** [comment]
Fixed widget link in [1490ec9](https://github.com/loadimpact/k6-docs/commit/1490ec967ff41f31b4b209895470fd8d850a6b9a)
