### ISSUE TITLE
Messed up home navigation

### ISSUE THREAD

**Issue by na--** [loadimpact/k6-docs#65]
We've committed the cardinal sin of forums, blogs and docs - there's no way to get back to the main site... 
The link on the top left of https://k6.io/docs/ leads to https://k6.io/docs/, not https://k6.io/
Same, the top left link in https://community.k6.io/ leads to https://community.k6.io/

**Comment by ppcano** [comment]
This is intentional. The main site link is fixed on the sidebar bottom.

<img width="305" alt="Screen Shot 2020-08-02 at 8 20 33 PM" src="https://user-images.githubusercontent.com/825430/89129445-b6fbef80-d4fd-11ea-80f2-e0d17289a8b4.png">

**Comment by ppcano** [comment]
FYI @majavojnoska. 



The Blog and Main Site have the same header. The Docs are different as shown above.

I am not sure what is better for https://community.k6.io/

Closing this issue
