### ISSUE TITLE
CookieJar.set documentation is wrong, only the example is correct

### ISSUE THREAD

**Issue by atorma** [loadimpact/k6-docs#80]
The documented api is `CookieJar.set(name, value, [options])`. However, there is an example

```
jar.set('https://httpbin.org/cookies', 'my_cookie', 'hello world', {
    domain: 'httpbin.org',
    path: '/cookies',
    secure: true,
    max_age: 600,
});
```

which suggests the api is `CookieJar.set(url, name, value, [options])`. This is correct. Calling `CookieJar.set` with cookie name as the first parameter results in no cookies set.

**Comment by na--** [comment]
@atorma, thanks for reporting this, indeed, the docs are wrong, `url` is the first parameter ([proof](https://github.com/loadimpact/k6/blob/248f556131bc8650cd4ac4080dae56a9bd630755/js/modules/k6/http/cookiejar.go#L66-L67))

**Comment by mostafa** [comment]
Thank you @atorma for your contribution. It's fixed now.

**Comment by atorma** [comment]
Great, cheers!
