### ISSUE TITLE
Welcome on the top of the "Getting started" isn't clickable

### ISSUE THREAD

**Issue by MStoykov** [loadimpact/k6-docs#84]
![image](https://user-images.githubusercontent.com/312246/90388637-c8fa9800-e090-11ea-97d0-db329f265a4a.png)

**Comment by BolotskyDev** [comment]
Fixed in [584f94c](https://github.com/loadimpact/k6-docs/commit/584f94c956094ff013cd71453f2ed660255141e7) ✅  Thank you for noticing!
