### ISSUE TITLE
Document plugins

### ISSUE THREAD

**Issue by na--** [loadimpact/k6-docs#85]
After we merge this k6 WIP PR: https://github.com/loadimpact/k6/pull/1396 (https://github.com/loadimpact/k6/issues/1353), but before we release k6 v0.28.0, someone has to write a docs page that explains plugins, and maybe has a very short and simple tutorial on how to write one. We should then link to that page from the v0.28.0 release notes. 

Also prompted by https://github.com/loadimpact/k6/issues/1595

Edit: as I've said many times, it's very important to stress in that docs page that this is a beta-quality feature. The current plugin API (and k6 APIs they will depend on) are not guaranteed to be stable, and plugins may need changes when we update k6.

**Comment by na--** [comment]
And, as was pointed out in https://github.com/loadimpact/k6/issues/1595, in the plugin writing docs, it might not be a bad idea to point out that the k6 built-in modules in https://github.com/loadimpact/k6/tree/master/js/modules/k6 might offer useful usage examples to plugin writers as well. Even though the quality of some of that code might be in dire need of improvement... :sweat_smile:

**Comment by simskij** [comment]
Things to do as part of this issue, in my opinion:

- [ ] Docs page that explains the API, the anatomy of a plugin, and the limitations of the current implementation @loadimpact/load-generator 
- [ ] Template repo at k6io/example-plugin. @mostafa or @simskij?

**Comment by mostafa** [comment]
@simskij and @na--,

1. I can write the docs article and the blog post.
2. I've made a messy [template repo](https://github.com/mostafa/k6-plugin-template) for the very same reason/cause, which can be improved to reflect the latest changes the plugin support PR.

**Comment by simskij** [comment]
Superseded by #169
