### ISSUE TITLE
Mention the DefinitelyTyped k6 type definitions

### ISSUE THREAD

**Issue by na--** [loadimpact/k6-docs#89]
https://k6io.slack.com/archives/C3E688J8Z/p1597785761016100 made me realize we don't have any place in the docs we can point users to when they are looking for this type of info... 

And that https://www.npmjs.com/package/@types/k6 is old, `0.26.1` :disappointed: I think we only have to add `scenarios` in https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/k6/options.d.ts , but I've never written a line of TypeScript and have no idea how to encode the complicated situations with different option keys possible in each scenario, based on the `executor` type :sob:

**Comment by ppcano** [comment]
Closed by https://github.com/loadimpact/k6-docs/pull/123 and https://github.com/DefinitelyTyped/DefinitelyTyped/pull/48315
