### ISSUE TITLE
Various minor issues

### ISSUE THREAD

**Issue by na--** [loadimpact/k6-docs#93]
We received a very detailed report from a user on Slack about various discrepancies in the docs: https://k6io.slack.com/archives/C5C0281HB/p1598167979001200

Pasting a screenshot here, since the public k6 slack doesn't keep messages forever: 
![Screenshot_2020-08-24 Slack documentation k6](https://user-images.githubusercontent.com/3336773/91036689-754bf980-e610-11ea-918c-063ceae00c1d.png)

**Comment by Senney** [comment]
@na-- I've opened a PR to correct the "entry" key (https://k6.io/docs/using-k6/modules#configuring-webpack) here:
https://github.com/loadimpact/k6-docs/pull/107

**Comment by na--** [comment]
Thanks, @Senney!
